import { TaskProvider } from '@/context/taskContext'
import './globals.css'
import { Inter, Roboto_Mono } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { Toaster } from './Toaster'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

export const metadata = {
  title: 'Context crud app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="es" className={`${inter.variable} ${roboto_mono.variable}`}>

      <body className={`${inter.className} bg-gray-800`}>
        <TaskProvider>
          <Navbar />
          {children}
          <Toaster position="bottom-left"
            reverseOrder={false} />
        </TaskProvider>
      </body>

    </html>
  )
}
